pipelines:
  docker-build:
    group: default
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      GODATA: "godata"
      PKG_NAME: "django-app-v0_1.zip"
    materials:
      git:
        git: https://github.com/madhuchary/django-app.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - docker:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          docker-build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                - -t
                - django:v0.1
                - .
                command: docker
                run_if: passed
  test-app:
    group: default
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/madhuchary/django-app.git
        branch: master
      upstream:
        pipeline: docker-build
        stage: docker
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
          artifacts:
          - build:
              source: django-app-v0_1.zip
            timeout: 0
            tasks:
            - exec:
                arguments:
                - test.sh
                command: bash
  publish:
    group: default
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/madhuchary/django-app.git
        shallow_clone: false
        auto_update: true
        branch: master
      upstream:
        pipeline: test-app
        stage: test
    stages:
    - publish:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: true
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          s3:
            timeout: 0
            artifacts:
            - external:
                id: django-app
                store_id: s3
                configuration:
                  options:
                    Source: django-app-v0_1.zip
                    Destination: django-app-v0_1.zip
            tasks:
            - exec:
                arguments:
                - Thanks GoCD
                command: echo
                run_if: passed
