format_version: 3
pipelines:
  run:
    group: default
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/madhuchary/django-app.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - docker:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          docker-build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                - -t
                - django
                - .
                command: docker
                run_if: passed

